### PR TITLE
Added scanned documents provided by @RenownMDK and converted

### PR DESCRIPTION
**Pull request by the-grue**
to searchable .pdf by @the-grue.

### CODE REVIEW

**Comment by andrewbird** [comment]
Hi @the-grue your searchable pdfs look great and are very lightweight. What tools did you use for conversion?

**Comment by the-grue** [comment]
Thanks @andrewbird!  I use a couple of free Linux based tools:

- img2pdf to convert all of the scan images into a pdf file
- ocrmypdf to do the OCR processing.  This uses Tesseract.

I have also used a script called shrinkpdf which tries to reduce the size of the finished file using "lossy recompression".  I think I only used this on the v4 documentation.  With the rest of them I just used the two tools above with some additional parameters.

**Comment by andrewbird** [comment]
@the-grue Thanks. I'm playing with `ocrmypdf` and I got some fairly good results, though I'm now trying again with uncompressed images, which I think should help. I have a 900 page doc that has a beige background, so I expect it to be large as the input pdf size has now risen from 100Mb to 1Gb - eek!

**Comment by andrewbird** [comment]
A follow up: With the uncompressed images after all the processing by ocrmypdf it resulted in a final pdf size of 100Mb, that is better than my previous attempt and is searchable too! Thanks again!

**Comment by the-grue** [comment]
Not bad!  You could try running it through shrinkpdf and see if it works for you.  It might be able to do a little better.  Worst case, you waste some CPU cycles.

**Pull request merged**
