### PR TITLE
automate build with dosemu2

### PR DESCRIPTION
**Pull request by stsp**
This needs a dosemu2 from git branch devel.
This successfully builds only the MOS kernel so far.

### CODE REVIEW

**Comment by andrewbird** [comment]
I suspect this will fix #5 too

**Comment by stsp** [comment]
Likely so.
So if we say "fixes #5" right here, will github understand that? :)

**Comment by stsp** [comment]
Updated patch.

**Comment by stsp** [comment]
I'll update the patch when this is fixed:
https://github.com/stsp/dosemu2/issues/526
So far dosemu2 is incapable of building MOS.
And has a lot of problems running it, too. :(

**Comment by stsp** [comment]
Updated patch.
Seems to build everything fine (not only kernel).

**Comment by stsp** [comment]
> This needs a dosemu2 from git branch devel.

These days not any more.

**Pull request merged**
