### PR TITLE
ACU.EXE now builds, beginning distribution assembly.

### PR DESCRIPTION
**Pull request by the-grue**
Reverse engineered stdusr.h from acu.exe to allow for build.
Updated makefile to not try to build/use missing executables.
Copied missing files into acu directory from distribution.
Created batch file to build acu.exe and begin distribution assembly.

### CODE REVIEW

**Comment by src153** [comment]
I'm curious how you figured out the .h values from the .exe.

When you get your distribution ready, it seems like a good idea to explain to potential users that it contains s a large amount of 5.02 development code not present in the official 5.01 release.

I will try to put together a more strict 5.01, as discussed elsewhere. Should not be too hard after you blaze the trail. But I don't know when, since I am distracted by many things.

**Comment by the-grue** [comment]
> As a collaborator, I think you should be able to push to the main repo now. Am I wrong? I might even have to learn this github stuff now.

I won't commit anything until it passes review by at least one other collaborator.  Otherwise we'll have the Wild West going on in here.

**Comment by the-grue** [comment]
> I'm curious how you figured out the .h values from the .exe.

Sure, glad to share.  I went through an iterative build process where I assigned each missing #define a bit position (1, 2, 4, etc.) as its value when it generated an error in the compile.  Then, when everything successfully built, it was obviously still broken because I didn't pick a single number correctly (kind of like when I play the lottery).  Then I went through and assigned each one a unique value, such as 0xBEE5, 0xDEAF, etc.  Then built, disassembled (ndisasm in this case), and used a diff tool (meld in this case) to compare the disassembly side-by-side and look for the discrepancies.  There are many because the version in the repo isn't an exact size or checksummed match with the one in the distribution, but I was able to find my values and associate them with the values they should be from the original executable and change it so it was accurate in the .h file.

From there, it was build, test, identify any values that were still wrong, and repeat until I had all of the variables set to the correct values and the acu.exe program behaves as advertised in the manual.
 
> When you get your distribution ready, it seems like a good idea to explain to potential users that it contains a large amount of 5.02 development code not present in the official 5.01 release.

Of course, that will be a given.  Plus, anything that builds out of latest as the source will be easily identifiable as such.  The work I am doing now is to get the other directories in line for building and they can be used by any of the source trees since they actually reside outside any one of the kernel/util/term directories.
 
> I will try to put together a more strict 5.01, as discussed elsewhere. Should not be too hard after you blaze the trail. But I don't know when, since I am distracted by many things.

No worries.  As I mentioned above, you should be able to fold in acu.exe as well as (soon) hdsetup.exe, install.exe, and export.exe.

**Comment by sub205** [comment]
In my personal oppinion, the golden way would be a 5.01a release which only fixes the y2k16-bug and despite this is 100% identical to the official 5.01.
After that, we can check the pending patches and things in the source tree and prepare a 5.02.
Step by step, otherwise we get only into chaos.

**Comment by src153** [comment]
@sub205 That's what I have in mind, with one tweak: Also apply the small typo patch Stas submitted. It's obviously wrong unpatched. If you want to do the work to make it so, don't wait for me.

**Comment by src153** [comment]
@sub205 I want to be sure we can prouduce an identical 5.01a $$mos.sys two ways:

a) binary patch to $$mos.sys in the 5 user system disk directory
b) built from source using $$eval, renamed to $$mos.sys, as the make file does, with the date patch and Stas type patch included

b) may be tricky, because when you first build $$mos.sys and boot it, the serial number is some X0X0... junk. How they get from that, to an actual serial number, as you see in the 5 user official disk, is unknown to me at this time. @the-grue may already know ...

**Comment by the-grue** [comment]
> b) may be tricky, because when you first build $$mos.sys and boot it, the serial number is some X0X0... junk. How they get from that, to an actual serial number, as you see in the 5 user official disk, is unknown to me at this time. @the-grue may already know ...

You can set the serial to whatever you want.  It looks like the first two digits is the number of users.  After that, 50000000, 50000001, etc.  The serial number is called "enbedded" in mosinit2.asm.  I have actually pulled that out and put it in an include file, with plans to allow custom number generation as part of the build.  Not top of list, but if you want, you could set it to exactly what it is in the 5 user disk and proceed from there.

Let me know if you want an assist with the binary patch of $$MOS.SYS.

**Comment by src153** [comment]
> You can set the serial to whatever you want. It looks like the first two digits is the number of users. After that, 50000000, 50000001, etc. The serial number is called "enbedded" in mosinit2.asm.

Thanks for the hint, I'll look into it. Some of these good anwers need to go in the wiki.

> Let me know if you want an assist with the binary patch of $$MOS.SYS.

sub205 expressed an interest in the work, so I offered it. I'd rather delegate than do it myself. We'll see if that goes anywhere.

**Comment by sub205** [comment]
For Linuxusers:

The commandline
`cat image_file_bad | hexdump -v -e '1/1 "%02X "' | sed 's/32 C0 26 8A 84 0D 00 80 FC 41 72 07 80 FC 5A 77/32 C0 26 8A A4 0D 00 80 FC 41 72 07 80 FC 5A 77/' | xxd -r -p> image_file_good
`
creates a patched "image_file_good" from the buggy "image_file_bad" and fixes the 2012-bug there.

**Comment by sub205** [comment]
Linux command to find buggy $$MOS.SYS and binary position:

grep -obarUP "\x32\xC0\x26\x8A\x84\x0D\x00\x80" .

Created a pull request and patched shipmos + v4

**Comment by the-grue** [comment]
@src153 this change won't impact your builds now.

**Pull request merged**
