### PR TITLE
Build01

### PR DESCRIPTION
**Pull request by andrewbird**
Some tweaks to help with the build
1/ Remove the files that are currently built, so that git doesn't consider them changed afterwards
2/ Extract DEBUG.COM from SHIPMOS.ZIP into /bin so that the kernel build can use it to fixup $$mos.sys
3/ Switch around the kernel build so that the non evaluation $$mos.sys is built by default.

### CODE REVIEW

**Comment by the-grue** [comment]
Hi @andrewbird !  For 1004cea, I have a different idea I have been working with and it covers all of the directories, not just the kernel and mos5src.  What I propose is that we keep the build objects that are part of the current repo as reference objects.  This way, when we build something, we can check to see if/what changed in the previous build.

What I have done is move any rebuildable objects (.zip, .lib, .obj, .map, .sys, .com, .exe, etc.) into a "ref" subdirectory.  This cleans up the build directory and leaves these reference objects in place.  This is in my current git at home and I haven't uploaded it yet.  I will offer it as an option/alternative to removing them from the tree entirely until we get a first open build of everything, not just the pieces makemos.bat rebuilds.

**Comment by andrewbird** [comment]
Sure I don't mind if you want to move them out of the way instead. The main thing for me is that after the build has  run doing `git diff` or `git commit -a` shouldn't reference anything but source file changes.

**Comment by the-grue** [comment]
Ok, I'll get a pull request done up as soon as I can and we can review it along with yours.

**Comment by the-grue** [comment]
Hi @andrewbird!  Please review #34 as an alternative to pruning the legacy build artifacts.

**Comment by andrewbird** [comment]
I force pushed the branch without the tidy up commit. Should not conflict with #34 PR now

**Pull request merged**
