### PR TITLE
added fixed v501 images and empty bootable floppy template

### PR DESCRIPTION
**Pull request by sub205**

### CODE REVIEW

**Comment by sub205** [comment]
Here are fixed v5.01 images and an empty bootable floppy for further automation of image creation, which i'll try to do next.

**Comment by andrewbird** [comment]
Hi @sub205 I don't want to be prescriptive, I don't know the context of your submission and might I suggest that you squash the multiple commits to the same file? In essence a single commit should encompass a single functional change. The idea behind this, although not particularly relevant for you, is that should a problem occur with a change somewhere, it's less revisions to bisect, test and isolate the breaking change. So for your case your textual changes could be a single commit, and your add image might be another.
Hope it helps,
Andrew

**Comment by andrewbird** [comment]
Oh I forgot one thing. If you commit to local branch other than master it's easy to do 
`git checkout master`
`git pull upstream master`
`git checkout your_work_branch`
`git rebase master`
so that you don't have to keep merging in the current upstream which confuses what exactly your changes are.

**Comment by roelandjansen** [comment]
great! Guys, this is exactly how we should treat eachother!

**Comment by sub205** [comment]
@andrewbird Thanks for the nice infos. I'm quite new to collaborative working, i only learned that it's better to fork and merge back than working directly in master ;-) I'll promise to do it better next time!

@roelandjansen In germany we have a saying ... it's like "the sound makes the music". When someone is acting like the biggest teacher and between every sentence is something like "you have no clue, i'm the best", that isn't really helping your contribution and mindset.

Nobody is perfect!

**Comment by sub205** [comment]
another question arises: Which is the preferred build environment for us? It's quite easy for me to do a packaging-script in linux, but wouldn't help much under DOS.

Especially mounting floppy images.

Dosbox offers a way to do this and may be the best solution?

**Comment by andrewbird** [comment]
@sub205 yes it can be difficult transition to collaborative working, but you shouldn't worry too much about format etc. Some projects have strict guidelines about submissions, here no guidelines  have been set but in general limiting what a potential reviewer has to do will ease patch submission. I myself use Linux exclusively but understand that others may not, particularly as this project is DOS oriented, so I tend to code for the DOS solution, whilst quietly ensuring that it works on Linux.

**Comment by roelandjansen** [comment]
my base is linux too and for testing I use vmware.

**Comment by the-grue** [comment]
My primary development platform is DosBox on Linux.  This allows me to use all of my Linux tools on the files while still in my DosBox session as well as direct access to git.  

I use VirtualBox for my actual "running" tests with both DOS 5 and MOS.  Now that the date bug is fixed, I don't really have much need for DOS anymore, but I still have it around if I need it.  I am able to run the required tools on MOS without much headache.

Once I have "something" I feel is ready for an actual test, I have a MOS "server" that has a couple built in serial ports, a Pentium 4 MOS laptop, and an old Compaq 486 laptop to run tests on.

So it looks like we have quite a broad set of platforms represented as dev/test environments!

**Pull request merged**
