### PR TITLE
Travis: Add initial build integration

### PR DESCRIPTION
**Pull request by andrewbird**
This PR adds support for PC-MOS to be built automatically on any potential PR merge and shows the maintainer that at least the build is not broken by it.

### CODE REVIEW

**Comment by andrewbird** [comment]
@roelandjansen to make this work as intended you'll need to follow the steps here https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github

**Comment by andrewbird** [comment]
Oh here's a link to the build https://travis-ci.com/github/andrewbird/pcmos386 click on the triangle next to `./travis_build` to see the build log

**Comment by andrewbird** [comment]
@stsp has requested some changes so I converted to a draft PR for now.

**Comment by stsp** [comment]
Were you able to get rid of an errors in the log?
If so, could you please update an URL to the log?

**Comment by andrewbird** [comment]
Just retesting the error filter now that the `-q` issue is solved.

**Comment by andrewbird** [comment]
I'm happy for this to be merged (subject to your review) now that Dosemu2 has the DOSEMU_QUIET env variable to suppress some spurious startup warnings that occur in the Travis environment.

**Comment by roelandjansen** [comment]
nice!

**Comment by andrewbird** [comment]
It's great that you merged it, thanks Have you done the travis integration with github (see above) yet, as only then will each commit and PR merge get checked automatically?

**Comment by roelandjansen** [comment]
not yet, lack of time.

**Pull request merged**
