### PR TITLE
MAKEMOS.BAT: rename moxcptsk.com command.com [#95]

### PR DESCRIPTION
**Pull request by stsp**
As was pointed out, this is how command.com should be built.

### CODE REVIEW

**Comment by the-grue** [comment]
If folks used the makeall.bat build process I developed, this is already in there.

**Comment by stsp** [comment]
This is only for MAKEMOS.BAT.
I wonder if something else is needed,
i.e. it produces the bootable system so
I always used it.

**Comment by the-grue** [comment]
My build process generates random serial numbers and inserts them into the kernel as well as providing activation on installation.  These functions are add-ons I coded separate from the original source and are just there to bypass the 60 minute kill timer.  Just a convenience to the user really, but if you aren't calling those bits, you should just get the standard distro with the 60 minute countdown.

**Comment by stsp** [comment]
But it doesn't say anything about a
60minutes demo:
Снимок экрана от 2020-05-06 00-20-35

Should I worry?
Also isn't it possible to kill the timer
in the code once and for all?

**Comment by the-grue** [comment]
> Should I worry?

Only way to know for sure is to wait an hour and see if it times out.  Does it say anything after you go through the date/time entries?  I thought it at least said something about the number of users it is licensed for and it should tell you if it is a 60 minute demo or not.

> Also isn't it possible to kill the timer
> in the code once and for all?

I am sure it is.  That's what I did with the CDROM driver.  This was just the solution I chose at the time.  I looked it and there is some ugly code surrounding the "copy protection" so this seemed easier.

**Comment by stsp** [comment]
Снимок экрана от 2020-05-06 00-35-55

Doesn't seem to be saying anything
interesting.
I did `git clean -fd` `git reset --h` and full
rebuild to make sure there are no unexpected
changes.

**Comment by stsp** [comment]
Even with this change:
```
diff --git a/SOURCES/src/latest/MOSSAVER.ASM b/SOURCES/src/latest/MOSSAVER.ASM
index b54f04f..9db5a28 100644
--- a/SOURCES/src/latest/MOSSAVER.ASM
+++ b/SOURCES/src/latest/MOSSAVER.ASM
@@ -295,7 +295,7 @@ gdata       segment
        extrn   intsl:byte,irqwflag:byte
 gdata  ends
 
-demoout equ    65520           ; 60*60*18.2 or 60 minutes
+demoout equ    655             ; 60*60*18.2 or 60 minutes^M
 
 irq    segment
        extrn   irqstart:byte, irqend:byte
```

it works rather well.
So I really think its cracked.

**Comment by andrewbird** [comment]
I think in the early days I set the kernel to be built as the r&d version which doesn't have the timeout. You may both be building in different directories depending upon which build script is used.

**Comment by stsp** [comment]
What commit was that?
I can't find.

**Comment by andrewbird** [comment]
063efe83492e3658c42797a36b35035cd9cf65ac

**Comment by stsp** [comment]
Ahha!
So I am using the right build after all. :)
Thanks.

**Comment by andrewbird** [comment]
Mm that may not be true. @the-grue has done lots of work since including fixing the date bug, I really couldn't say!

**Comment by stsp** [comment]
My build also builds in src/latest, so I think
it misses nothing. Just different make targets
perhaps.

**Comment by the-grue** [comment]
As long as you are building out of latest, you should be ok.  I based my work off the EVAL version since that was considered "retail" and I wasn't sure what, if any, differences there were between EVAL and the in-house version.  

I would imagine that change made to the demoout variable would just result in it locking up after a few minutes instead of 60 under the EVAL version.  I honestly don't think it is that simple to get around or anyone with a hex editor could have broken their copy protection.  Then again...date bug, so who knows.  There may be a simple short-circuit in there and maybe it is as easy as building in-house vs eval.  Maybe something to consider for v6!

makemos.bat does not rebuild everything however and may be more suitable if you are just rebuilding parts of the environment (kernel and utils).  My build scripts rebuild the entire system and results in a floppy image you can install from.  Either way, you should be getting an up-to-date kernel and basic utilities built out of the latest directory.  

This won't include the cdrom driver, the installer, or the hdsetup utility.  But if you want to hack on those, each directory has its own build processes and are pretty self contained.

It's always good to see new people getting interested in MOS.

**Comment by stsp** [comment]
> I would imagine that change made to the demoout variable would just result in it locking up after a 

Yes, that was the point of checking
whether my version is cracked or not,
w/o waiting for an hour.

**Pull request merged**
